@extends('layouts.app')

@section('content')
    @include('partials.admin-sidebar')
    <header class="panel topbar">
        <div><h1>WordPress Sites</h1><p class="muted">Manage site reporting and reporter credentials.</p></div>
        <form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="secondary">Sign out</button></form>
    </header>

    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
    @if(session('wordpressSiteCredentials'))<section class="panel content" style="margin:16px 0;border-color:#b66a00;"><h2>Copy WordPress Reporter Credentials Now</h2><p class="muted">These credentials are shown once. Save them in the WordPress reporter settings, then they will no longer be displayed here.</p><p><strong>Site:</strong> {{ session('wordpressSiteCredentials.siteName') }}</p><p><strong>Endpoint:</strong> <code>{{ session('wordpressSiteCredentials.endpoint') }}</code></p><p><strong>Token:</strong> <code>{{ session('wordpressSiteCredentials.token') }}</code></p></section>@endif

    <section class="panel content" style="margin-top:16px;"><h2>Add WordPress Site</h2><form method="POST" action="{{ route('wordpress-sites.store') }}" class="form-grid">@csrf<div><label for="wordpress-site-name">Site name</label><input id="wordpress-site-name" name="name" value="{{ old('name') }}" required><span class="error">@error('name'){{ $message }}@enderror</span></div><div><label for="wordpress-site-url">WordPress URL</label><input id="wordpress-site-url" name="url" type="url" placeholder="https://example.com" value="{{ old('url') }}" required><span class="error">@error('url'){{ $message }}@enderror</span></div><div style="align-self:end;"><button type="submit">Add WordPress site</button></div></form><p class="muted" style="margin:14px 0;">Install the <a href="{{ asset('downloads/serverdashboard-reporter.zip') }}">WordPress reporter plugin ZIP</a>. Production reporter endpoints require HTTPS; local HTTP works only when WordPress and the dashboard run on the same machine with WP_DEBUG enabled.</p></section>
    <section class="panel content" style="margin-top:14px;"><h2>Registered Sites</h2><div class="scroll"><table><thead><tr><th>Site</th><th>Status</th><th>Last report</th><th>Plugins</th><th>Updates</th><th>Security actions</th></tr></thead><tbody>@forelse($wordpressSites as $site)<tr><td><strong>{{ $site->name }}</strong><br><a href="{{ $site->url }}" target="_blank" rel="noopener noreferrer">{{ $site->url }}</a></td><td><span class="badge {{ $site->is_active ? 'ok' : 'danger' }}">{{ $site->is_active ? 'enabled' : 'disabled' }}</span></td><td>{{ $site->last_reported_at?->diffForHumans() ?? 'No report yet' }}</td><td>{{ $site->last_plugin_count }}</td><td><span class="badge {{ $site->last_outdated_count > 0 ? 'warning' : 'ok' }}">{{ $site->last_outdated_count }}</span></td><td><div class="actions"><form method="POST" action="{{ route('wordpress-sites.rotate-token', $site) }}">@csrf<button type="submit">Rotate token</button></form><form method="POST" action="{{ route('wordpress-sites.toggle-active', $site) }}">@csrf<button type="submit" class="secondary">{{ $site->is_active ? 'Disable reporting' : 'Enable reporting' }}</button></form></div></td></tr>@empty<tr><td colspan="6">No WordPress sites registered.</td></tr>@endforelse</tbody></table></div></section>
@endsection