<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root { --ink:#1f2937; --muted:#64748b; --surface:rgba(255,255,255,.9); --line:#d9e2ec; --teal:#0f766e; --teal-dark:#115e59; --gold:#a15c00; --red:#b42318; --green:#17803d; }
        * { box-sizing:border-box; } body { margin:0; min-height:100vh; color:var(--ink); font-family:"Segoe UI",Tahoma,sans-serif; background:radial-gradient(circle at 10% 10%,#e4f3ed 0,transparent 31%),radial-gradient(circle at 90% 80%,#f9e8cf 0,transparent 30%),#edf3f8; }
        .shell { max-width:1280px; margin:auto; padding:24px; } .panel { background:var(--surface); border:1px solid var(--line); border-radius:8px; box-shadow:0 8px 22px rgba(15,23,42,.07); } .topbar { display:flex; align-items:center; justify-content:space-between; gap:16px; padding:18px 20px; } h1,h2,h3,p { margin-top:0; } h1 { font-size:24px; margin-bottom:4px; } h2 { font-size:18px; } h3 { color:var(--muted); font-size:14px; margin-bottom:8px; } .muted { color:var(--muted); margin-bottom:0; } .actions { display:flex; gap:8px; flex-wrap:wrap; } button { appearance:none; border:0; border-radius:6px; padding:10px 13px; background:var(--teal); color:#fff; font-weight:700; cursor:pointer; } button:hover { background:var(--teal-dark); } button.secondary { background:#475569; } .meters { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:12px; margin:16px 0; } .meter { padding:16px; } .value { font-size:34px; font-weight:750; } .grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; } .wide { grid-column:1 / -1; } .content { padding:18px; } .chart-area { height:320px; } table { width:100%; border-collapse:collapse; } th,td { padding:10px 8px; text-align:left; border-bottom:1px solid var(--line); font-size:14px; vertical-align:top; } th { color:var(--muted); } .scroll { overflow-x:auto; } .badge { display:inline-block; padding:4px 8px; border-radius:999px; font-size:12px; font-weight:700; } .ok { color:var(--green); background:#dcf7e5; } .warning { color:var(--gold); background:#fff0d8; } .danger { color:var(--red); background:#fde8e7; } .pagination { display:flex; align-items:center; gap:10px; margin-top:10px; } .pagination button { padding:6px 10px; font-size:13px; } .pagination button:disabled { opacity:.5; cursor:not-allowed; } .notice { padding:12px 14px; margin:16px 0; color:var(--green); background:#dcf7e5; border:1px solid #bde9cb; border-radius:6px; } .form-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:10px; } label { display:block; font-size:13px; font-weight:700; margin-bottom:4px; } input,select { width:100%; padding:10px; border:1px solid #bfcbd7; border-radius:6px; background:#fff; } .error { color:var(--red); font-size:13px; margin-top:5px; } @media(max-width:800px){ .shell{padding:14px}.topbar{align-items:flex-start;flex-direction:column}.meters,.grid{grid-template-columns:1fr}.wide{grid-column:auto}.form-grid{grid-template-columns:1fr;} }
        .admin-sidebar { position:fixed; top:24px; left:max(24px,calc((100vw - 1280px) / 2)); width:190px; padding:16px 12px; } .admin-sidebar h2 { margin:0 0 10px; color:var(--muted); font-size:12px; letter-spacing:.08em; text-transform:uppercase; } .admin-sidebar nav { display:grid; gap:4px; } .admin-sidebar a { display:block; padding:10px 12px; color:var(--ink); border-radius:6px; font-size:14px; font-weight:700; text-decoration:none; } .admin-sidebar a:hover,.admin-sidebar a:focus,.admin-sidebar a.is-active { color:var(--teal-dark); background:#e1f2ee; } .shell:has(.admin-sidebar) { max-width:1070px; margin-right:max(24px,calc((100vw - 1280px) / 2)); margin-left:calc(max(24px,calc((100vw - 1280px) / 2)) + 210px); } @media (max-width:900px) { .admin-sidebar { position:static; width:auto; margin-bottom:16px; } .admin-sidebar nav { grid-template-columns:repeat(3,minmax(0,1fr)); } .shell:has(.admin-sidebar) { max-width:1280px; margin:auto; } } @media (max-width:640px) { .shell { padding:14px; } .topbar { align-items:flex-start; flex-direction:column; } .meters,.grid,.form-grid { grid-template-columns:1fr; } .admin-sidebar nav { grid-template-columns:1fr; } }
    </style>
</head>
<body>
    <main class="shell">@yield('content')</main>
</body>
</html>